import {api} from '../../services/api.js';
import {money,compact,percent,escapeHTML} from '../../utils/format.js';
import {renderAIRail} from '../../layouts/terminal-layout.js';
import {navigate} from '../../app/router.js';
import {asArray,isMounted} from '../../utils/safe.js';
import {skeleton} from '../../utils/render.js';

const chainName={bsc:'BSC',solana:'SOL',eth:'ETH',base:'BASE',arbitrum:'ARB',polygon:'POLYGON'};
const riskMeta={danger:{label:'\u5371\u9669',cls:'warn'},high:{label:'High',cls:'warn'},watch:{label:'Watch',cls:''},normal:{label:'Normal',cls:'up'}};
const ageFmt=t=>{if(!t)return'—';const h=Date.now()/1000-t;if(h<3600)return Math.max(1,Math.round(h/60))+'m';if(h<86400)return (h/3600).toFixed(1)+'h';return (h/86400).toFixed(1)+'d'};
const txFmt=b=>b==null?'—':Number(b).toLocaleString('en-US');
const debounce=(fn,ms)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};

export async function renderRadar(root){
  let timer,projects=[],sort='liquidity',chain='',query='',scanning=true,updated=0,first=true;
  root.innerHTML=skeleton({cards:0,panels:1,rows:8,cols:9});
  const rowHtml=(p,i)=>`<tr data-token="${escapeHTML(p.token)}" data-chain="${escapeHTML(p.chain)}" data-url="${escapeHTML(p.url||'')}" style="cursor:pointer"><td><div class="asset"><span class="asset-name"><b>${escapeHTML(p.symbol||p.name||'?')}${(p.created&&(Date.now()/1000-p.created)<86400)?' <em class="ex-badge">NEW</em>':''}</b><span style="max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${escapeHTML(p.name||'')}${p.description?` · ${escapeHTML(p.description.slice(0,60))}`:''}</span></span></div></td><td><span class="ex-badge">${chainName[p.chain]||escapeHTML(p.chain||'')}</span>${p.dex?`<small style="opacity:.55;margin-left:4px">${escapeHTML(p.dex)}</small>`:''}</td><td><b>${money(p.price_usd)}</b><br><small class="${Number(p.price_change_24h)>=0?'up':'down'}">${percent(p.price_change_24h)}</small></td><td>${compact(p.liquidity_usd)}</td><td>${compact(p.volume_24h)}</td><td><span class="up">Buy ${txFmt(p.buys_24h)}</span><br><span class="down">Sell ${txFmt(p.sells_24h)}</span></td><td>${compact(p.fdv)}</td><td>${ageFmt(p.created)}</td><td><span class="risk-badge ${riskMeta[p.risk_level]?.cls||''}" style="display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700;${p.risk_level==='danger'?'background:rgba(255,95,109,.18);color:#ff5f6d':p.risk_level==='high'?'background:rgba(255,159,67,.15);color:#ff9f43':p.risk_level==='watch'?'background:rgba(244,183,40,.15);color:#f4b728':'background:rgba(32,217,154,.14);color:#20d99a'}">${p.risk_score} ${riskMeta[p.risk_level]?.label||''}</span><div style="font-size:10px;opacity:.55;margin-top:2px">${asArray(p.risk_tags).slice(0,3).join(' · ')}</div></td></tr>`;
  const paint=()=>{
    if(!isMounted(root))return;
    const body=root.querySelector('#radarRows');if(!body)return;
    let list=projects;
    if(chain)list=list.filter(p=>p.chain===chain);
    if(query)list=list.filter(p=>(p.symbol||'').toLowerCase().includes(query)||(p.name||'').toLowerCase().includes(query));
    if(sort==='liquidity')list=[...list].sort((a,b)=>(Number(b.liquidity_usd)||0)-(Number(a.liquidity_usd)||0));
    else if(sort==='hot')list=[...list].sort((a,b)=>(Number(b.volume_24h)||0)-(Number(a.volume_24h)||0));
    else if(sort==='risk')list=[...list].sort((a,b)=>(Number(b.risk_score)||0)-(Number(a.risk_score)||0));
    else if(sort==='gain')list=[...list].sort((a,b)=>(Number(b.price_change_24h)||-9999)-(Number(a.price_change_24h)||-9999));
    else list=[...list].sort((a,b)=>(Number(b.created)||0)-(Number(a.created)||0));
    body.innerHTML=list.map(rowHtml).join('')||`<tr><td colspan="9" class="cg-empty">${scanning?'\u96f7\u8fbeScanning，\u6b63\u5728\u62c9\u53d6On-Chain\u6700\u65b0\u9879\u76ee…':'None\u9879\u76ee · \u70b9\u51fb「Refresh Now」Retry'}</td></tr>`;
    body.querySelectorAll('tr[data-token]').forEach((tr,i)=>tr.__proj=list[i]);
    root.querySelectorAll('#radarRows tr[data-token]').forEach(tr=>tr.onclick=e=>{if(e.target.closest('a'))return;const t=tr.dataset.token,ch=tr.dataset.chain;if(t)navigate('/v2/token/'+ch+'/'+t)});
    const stamp=root.querySelector('#radarStamp'),cnt=root.querySelector('#radarCount');
    if(stamp)stamp.textContent=(scanning?'Scanning…':'LIVE')+(updated?' · '+new Date(updated*1000).toLocaleTimeString('zh-CN',{hour12:false}):'');
    if(cnt)cnt.textContent=list.length+'  Assets\u9879\u76ee';
  };
  const load=async(force=false)=>{
    try{
      const r=await api.radarProjects(sort,chain,query,force);
      projects=asArray(r.projects);scanning=!!r.scanning;updated=r.updated_at||0;
      if(first){first=false;root.querySelector('#radarList')?.classList.remove('hidden')}
      paint();
      if(scanning&&!projects.length)setTimeout(()=>load(false),4000);
    }catch{scanning=false;paint()}
  };
  root.innerHTML=`<div class="page-head"><div><h1>On-Chain Radar</h1><p>AI On-ChainProject Radar · NEW PAIRS · LIQUIDITY · RUG RISK SCAN</p></div><div class="page-actions"><span class="status-live" id="radarStamp">● Scanning…</span><button id="radarRefresh" class="terminal-btn">Refresh Now</button></div></div>
  <section class="panel" style="margin-bottom:12px"><div class="panel-head"><h2>ON-CHAIN INTELLIGENCE</h2><span>PHASE 1 · ETHEREUM / BSC · BACKEND DATA ONLY</span></div><form id="ociForm" class="toolbar" style="padding:14px"><select id="ociChain" class="terminal-select"><option value="bsc">BSC</option><option value="eth">Ethereum</option></select><input id="ociToken" class="terminal-input" style="flex:1" placeholder="\u8f93\u5165 Token Contract Address（0x…）" autocomplete="off" spellcheck="false"><button class="terminal-btn primary" id="ociAnalyze">Generate Token Profile</button></form><div id="ociProfile"></div></section>
  <div class="toolbar"><input id="radarSearch" class="terminal-input" placeholder="SearchTokenSymbol / Name / Contract Address…"><div style="display:flex;gap:6px;margin-left:auto;flex-wrap:wrap"><button class="terminal-btn ${sort==='liquidity'?'primary':''}" data-sort="liquidity">💧 Liquidity</button><button class="terminal-btn ${sort==='new'?'primary':''}" data-sort="new">🆕 New Listings</button><button class="terminal-btn ${sort==='hot'?'primary':''}" data-sort="hot">🔥 Trending</button><button class="terminal-btn ${sort==='gain'?'primary':''}" data-sort="gain">📈 Gainers</button><button class="terminal-btn ${sort==='risk'?'primary':''}" data-sort="risk">⚠️ High</button></div></div><div class="toolbar" style="margin-top:8px"><span style="font-size:12px;opacity:.6;margin-right:8px">Chain:</span><button class="terminal-btn ${chain===''?'primary':''}" data-chain="">All</button><button class="terminal-btn ${chain==='bsc'?'primary':''}" data-chain="bsc">BSC</button><button class="terminal-btn ${chain==='solana'?'primary':''}" data-chain="solana">SOL</button><button class="terminal-btn ${chain==='eth'?'primary':''}" data-chain="eth">ETH</button><button class="terminal-btn ${chain==='base'?'primary':''}" data-chain="base">BASE</button><button class="terminal-btn ${chain==='arbitrum'?'primary':''}" data-chain="arbitrum">ARB</button><button class="terminal-btn ${chain==='polygon'?'primary':''}" data-chain="polygon">POLYGON</button><span id="radarCount" style="margin-left:auto;font-size:12px;opacity:.6"></span></div><section class="panel" id="radarList" style="margin-top:12px"><div class="panel-head"><h2>PROJECT MATRIX</h2><span>RISK SCAN · AI RULES ENGINE</span></div><div class="table-scroll"><table class="market-table pro-table no-click"><thead><tr><th>PROJECT</th><th>CHAIN</th><th>PRICE</th><th>LIQUIDITY</th><th>VOL 24H</th><th>TXNS 24H</th><th>FDV</th><th>AGE</th><th>AI RISK</th></tr></thead><tbody id="radarRows"><tr><td colspan="9" class="cg-empty">LoadingOn-Chain\u9879\u76ee…</td></tr></tbody></table></div></section>`;
  const noData=(r)=>`<div class="empty-page" style="padding:24px"><b>No Data</b><p>API: ${escapeHTML(r?.api_status||'degraded')} · ${escapeHTML(r?.error||'\u4e0a\u6e38No data')}</p><small>\u6700\u540eUpdated：${r?.update_time?new Date(r.update_time*1000).toLocaleString('zh-CN'):'—'}</small></div>`;
  const profileHtml=r=>{
    if(!r||r.status==='error'||!r.data)return noData(r);
    const d=r.data,h=d.holders||{},dist=h.distribution||{},ha=h.analytics||{},p=d.pools||{},tr=(d.trades||{}).trades||[],pools=p.pools||[],holders=h.holders||[];
    const updated=r.update_time?new Date(r.update_time*1000).toLocaleString('zh-CN'):'—';
    return `<div style="padding:0 14px 14px"><div class="overview-grid" style="margin:0 0 12px"><article class="metric-card"><div class="metric-label">HOLDERS</div><div class="metric-value">${Number(h.holder_count||0).toLocaleString()}</div><div class="metric-sub">\u589e\u957f ${ha.holder_growth_rate==null?'No Data':percent(ha.holder_growth_rate)}</div></article><article class="metric-card"><div class="metric-label">LIQUIDITY</div><div class="metric-value">${compact(p.total_liquidity)}</div><div class="metric-sub">${p.liquidity_risk?.liquidity_decline?'LP Liquidity\u4e0b\u964d':'LP Status\u7a33\u5b9a/None\u5386\u53f2'}</div></article><article class="metric-card"><div class="metric-label">SMART MONEY</div><div class="metric-value">${d.smart_money?.matched_wallets||0}</div><div class="metric-sub">\u8bc4\u5206 ≥ 70</div></article><article class="metric-card"><div class="metric-label">RISK SCORE</div><div class="metric-value ${Number(d.risk_score)>=70?'down':'up'}">${Math.round(Number(d.risk_score||0))}</div><div class="metric-sub">0 LOW · 100 HIGH</div></article></div>
    <section class="panel"><div class="panel-head"><h2>HOLDER DISTRIBUTION</h2><span>Top10 ${Number(dist.top10||0).toFixed(2)}% · Top50 ${Number(dist.top50||0).toFixed(2)}% · Others ${Number(dist.others||0).toFixed(2)}%</span></div><div style="padding:12px"><div style="height:14px;display:flex;border-radius:7px;overflow:hidden;background:#243040"><i style="width:${Math.min(100,dist.top10||0)}%;background:#ff5f6d"></i><i style="width:${Math.max(0,(dist.top50||0)-(dist.top10||0))}%;background:#f4b728"></i><i style="flex:1;background:#20d99a"></i></div><p style="font-size:12px">AI：${escapeHTML(ha.ai_analysis||'No Data')} · \u5de8\u9cb8Share ${Number(ha.whale_percentage||0).toFixed(2)}%</p><div class="toolbar"><button class="terminal-btn primary" type="button" data-holder-limit="10">Top 10 Holders</button><button class="terminal-btn" type="button" data-holder-limit="50">Top 50 Holders</button></div><div class="table-scroll"><table class="market-table"><thead><tr><th>#</th><th>WALLET</th><th>BALANCE</th><th>PERCENT</th><th>CHANGE</th><th>LABEL / SCORE</th></tr></thead><tbody id="ociHolderRows">${holders.slice(0,10).map((x,i)=>`<tr><td>${i+1}</td><td title="${escapeHTML(x.wallet_address)}">${escapeHTML(String(x.wallet_address).slice(0,8))}…${escapeHTML(String(x.wallet_address).slice(-6))}</td><td>${compact(x.balance)}</td><td>${Number(x.percentage||0).toFixed(3)}%</td><td class="${Number(x.change)>=0?'up':'down'}">${compact(x.change)}</td><td>${escapeHTML(x.label||'—')} ${Number(x.smart_money_score||0).toFixed(0)} <button class="terminal-btn" style="padding:2px 6px" data-label-wallet="${escapeHTML(x.wallet_address)}">\u6253Tags</button></td></tr>`).join('')||'<tr><td colspan="6" class="cg-empty">No Data</td></tr>'}</tbody></table></div></div></section>
    <section class="panel" style="margin-top:12px"><div class="panel-head"><h2>LIQUIDITY POOLS</h2><span>API ${pools.length?'ONLINE':'NO DATA'}</span></div><div class="table-scroll"><table class="market-table"><thead><tr><th>DEX</th><th>PAIR</th><th>LIQUIDITY</th><th>VOLUME 24H</th><th>TXNS</th><th>LP CHANGE</th></tr></thead><tbody>${pools.map(x=>`<tr><td>${escapeHTML(x.dex)}</td><td>${escapeHTML(x.pair)}</td><td>${compact(x.liquidity)}</td><td>${compact(x.volume_24h)}</td><td>${txFmt(x.tx_count_24h)}</td><td>${x.lp_change_24h==null?'No Data':percent(x.lp_change_24h)}</td></tr>`).join('')||'<tr><td colspan="6" class="cg-empty">No Data</td></tr>'}</tbody></table></div></section>
    <section class="panel" style="margin-top:12px"><div class="panel-head"><h2>LIVE BUY / SELL FLOW</h2><span>${tr.length} TRADES</span></div><div class="table-scroll"><table class="market-table"><thead><tr><th>SIDE</th><th>WALLET</th><th>AMOUNT</th><th>TOKEN</th><th>PRICE</th><th>TIME</th><th>DEX / LABEL</th></tr></thead><tbody>${tr.map(x=>`<tr><td class="${x.side==='BUY'?'up':'down'}">${escapeHTML(x.side)}</td><td>${escapeHTML(String(x.wallet_address||'').slice(0,10))}…</td><td>${money(x.amount_usd)}</td><td>${compact(x.token_amount)}</td><td>${money(x.price_usd)}</td><td>${x.timestamp?new Date(x.timestamp*1000).toLocaleTimeString('zh-CN'):'—'}</td><td>${escapeHTML(x.dex||'—')} · ${escapeHTML((x.labels||[]).map(v=>v.label).join(', ')||'—')}</td></tr>`).join('')||'<tr><td colspan="7" class="cg-empty">No Data</td></tr>'}</tbody></table></div></section><p style="opacity:.55;font-size:11px">\u6570\u636eStatus: ${escapeHTML(r.api_status||'—')} · \u6700\u540eUpdated: ${updated} · \u5ef6\u8fdf: ${r.delay||0}s</p></div>`;
  };
  const bindProfile=(result,tokenChain,tokenAddress)=>{
    const slot=root.querySelector('#ociProfile');if(!slot)return;slot.innerHTML=profileHtml(result);
    const holders=result?.data?.holders?.holders||[];
    slot.querySelectorAll('[data-holder-limit]').forEach(b=>b.onclick=()=>{slot.querySelectorAll('[data-holder-limit]').forEach(x=>x.classList.toggle('primary',x===b));const n=Number(b.dataset.holderLimit);const tb=slot.querySelector('#ociHolderRows');if(tb)tb.innerHTML=holders.slice(0,n).map((x,i)=>`<tr><td>${i+1}</td><td title="${escapeHTML(x.wallet_address)}">${escapeHTML(String(x.wallet_address).slice(0,8))}…${escapeHTML(String(x.wallet_address).slice(-6))}</td><td>${compact(x.balance)}</td><td>${Number(x.percentage||0).toFixed(3)}%</td><td class="${Number(x.change)>=0?'up':'down'}">${compact(x.change)}</td><td>${escapeHTML(x.label||'—')} ${Number(x.smart_money_score||0).toFixed(0)}</td></tr>`).join('')||'<tr><td colspan="6" class="cg-empty">No Data</td></tr>'});
    slot.querySelectorAll('[data-label-wallet]').forEach(b=>b.onclick=async()=>{const label=prompt('Wallet label (Smart Money / Whale / Institution / Exchange / Market Maker)','Smart Money');if(!label)return;try{await api.onchainWalletLabelSet({chain:tokenChain,wallet_address:b.dataset.labelWallet,label,score:0});b.textContent='Saved'}catch(e){alert(e.message)}});
  };
  root.querySelector('#ociForm').onsubmit=async e=>{e.preventDefault();const ch=root.querySelector('#ociChain').value,tk=root.querySelector('#ociToken').value.trim(),btn=root.querySelector('#ociAnalyze'),slot=root.querySelector('#ociProfile');btn.disabled=true;btn.textContent='\u5206\u6790Medium…';slot.innerHTML='<div class="cg-empty" style="padding:28px">\u6b63\u5728\u901a\u8fc7\u540e\u7aef\u91c7\u96c6\u5e76\u5206\u6790\u771f\u5b9eOn-Chain\u6570\u636e…</div>';try{const r=await api.onchainProfile(ch,tk,true);bindProfile(r,ch,tk)}catch(err){slot.innerHTML=noData({api_status:'degraded',error:err.message,update_time:Math.floor(Date.now()/1000)})}finally{btn.disabled=false;btn.textContent='Generate Token Profile'}};
  root.querySelector('#radarSearch').oninput=debounce(e=>{query=e.target.value.trim().toLowerCase();paint()},250);
  root.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{sort=b.dataset.sort;root.querySelectorAll('[data-sort]').forEach(x=>x.classList.toggle('primary',x===b));load(false)});
  root.querySelectorAll('[data-chain]').forEach(b=>b.onclick=()=>{chain=b.dataset.chain;root.querySelectorAll('[data-chain]').forEach(x=>x.classList.toggle('primary',x===b));paint()});
  root.querySelector('#radarRefresh').onclick=()=>{load(true);root.querySelector('#radarRefresh').textContent='Scanning…'};
  await load(true);
  timer=setInterval(()=>load(false),30000);
  renderAIRail();
  return()=>{clearInterval(timer)};
}
