import {api} from '../../services/api.js';
import {escapeHTML} from '../../utils/format.js';
import {asArray,asObject,isMounted} from '../../utils/safe.js';

const ACTIONS=[
  ['TOKEN_ANALYSIS','Analyze Token','BTC','Token Analyzer'],
  ['SMART_MONEY_ANALYSIS','Smart Money','Find smart money activity on ETH','Smart Money Finder'],
  ['RISK_SCAN','Risk Scan','Scan 0x... for contract risk','Risk Scanner'],
  ['MARKET_SUMMARY','Market Summary',"Summarize today's crypto market",'Market Overview'],
  ['ALPHA_DISCOVERY','Find Alpha',"Find today's strongest alpha signals",'Alpha Discovery'],
  ['NEWS_ANALYSIS','Crypto News','Summarize today’s crypto news','News Analyzer'],
  ['WALLET_ANALYSIS','Wallet Intelligence','Analyze wallet 0x...','Wallet Analyzer'],
  ['ONCHAIN_ANALYSIS','On-Chain Depth','Analyze ETH on-chain exchange flow','On-Chain Analyzer'],
  ['DERIVATIVES_ANALYSIS','Derivatives','Analyze BTC funding, OI and liquidations','Derivatives Analyzer'],
  ['TOKEN_COMPARE','Compare Tokens','Compare BTC versus ETH','Token Comparison'],
];
const MODE_ACTIONS={assistant:['TOKEN_ANALYSIS','MARKET_SUMMARY','RISK_SCAN','WALLET_ANALYSIS','NEWS_ANALYSIS'],alpha:['SMART_MONEY_ANALYSIS','ALPHA_DISCOVERY','ONCHAIN_ANALYSIS','DERIVATIVES_ANALYSIS','TOKEN_COMPARE']};
const fmt=value=>value==null||value===''?'—':typeof value==='number'?value.toLocaleString('en-US',{maximumFractionDigits:4}):String(value);
const compact=value=>{const number=Number(value);if(value==null||!Number.isFinite(number))return'—';if(Math.abs(number)>=1e12)return(number/1e12).toFixed(2)+'T';if(Math.abs(number)>=1e9)return(number/1e9).toFixed(2)+'B';if(Math.abs(number)>=1e6)return(number/1e6).toFixed(2)+'M';if(Math.abs(number)>=1e3)return(number/1e3).toFixed(1)+'K';return fmt(number)};
const requestId=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;

function coreHTML(displayName='AITRA'){
  const name=String(displayName||'AITRA').trim().slice(0,24)||'AITRA';
  const size=name.length<=6?25:name.length<=12?19:14;
  const lines=name.length>12?[name.slice(0,12),name.slice(12,24)]:[name];
  const labels=lines.map((line,index)=>`<tspan x="100" dy="${index?17:0}">${escapeHTML(line)}</tspan>`).join('');
  return `<div class="aitra-core" id="aitraCore" data-state="idle" aria-label="AITRA AI Core status: idle"><div class="aitra-core-scan"></div><div class="aitra-orbit orbit-a"><i></i><i></i></div><div class="aitra-orbit orbit-b"><i></i></div><div class="aitra-orbit orbit-c"></div><svg viewBox="0 0 200 200" aria-hidden="true"><defs><radialGradient id="coreGlow" cx="38%" cy="28%"><stop offset="0" stop-color="var(--text)" stop-opacity=".82"/><stop offset=".22" stop-color="var(--aitra-accent)" stop-opacity=".48"/><stop offset=".62" stop-color="var(--aitra-accent)" stop-opacity=".16"/><stop offset="1" stop-color="var(--surface)" stop-opacity=".92"/></radialGradient><linearGradient id="coreGlass" x1="0" y1="0" x2="1" y2="1"><stop stop-color="var(--text)" stop-opacity=".22"/><stop offset=".42" stop-color="var(--aitra-accent)" stop-opacity=".08"/><stop offset="1" stop-color="var(--surface-2)" stop-opacity=".42"/></linearGradient><filter id="coreBlur"><feGaussianBlur stdDeviation="3"/></filter></defs><circle cx="100" cy="100" r="70" fill="url(#coreGlow)" stroke="var(--aitra-accent)" stroke-opacity=".42"/><ellipse cx="78" cy="64" rx="37" ry="21" fill="url(#coreGlass)" transform="rotate(-24 78 64)"/><path d="M38 106c19 25 37 34 62 34s47-13 63-38" fill="none" stroke="var(--aitra-accent)" stroke-opacity=".12"/><circle cx="100" cy="100" r="75" fill="none" stroke="var(--aitra-accent)" stroke-opacity=".17" filter="url(#coreBlur)"/><text class="aitra-core-name" x="100" y="${lines.length>1?99:108}" text-anchor="middle" fill="var(--text)" font-size="${size}" font-weight="800" letter-spacing="${name.length<=6?3:1}">${labels}</text></svg><div class="aitra-stream"><i></i><i></i><i></i></div></div>`}

function reportHTML(raw){
  const report=asObject(raw),token=asObject(report.token),market=asObject(report.market),risk=asObject(report.risk),smart=asObject(report.smart_money),derivatives=asObject(report.derivatives);
  const sentiment=String(report.sentiment||'neutral').toLowerCase(),riskLevel=String(risk.level||'unknown').toLowerCase();
  const metrics=[['Price',market.price],['24H Change',market.change_24h==null?null:`${fmt(market.change_24h)}%`],['Market Cap',market.market_cap==null?null:compact(market.market_cap)],['24H Volume',market.volume_24h==null?null:compact(market.volume_24h)]];
  const derivativeRows=Object.entries(derivatives).slice(0,6);
  return `<article class="aitra-report"><header><div><span>AITRA INTELLIGENCE REPORT · ${escapeHTML(report.schema_version||'aitra.report.v1')}</span><h2>${escapeHTML(report.title||'Crypto Intelligence Report')}</h2><p>${escapeHTML(report.summary||'Validated intelligence from available data sources.')}</p></div><div class="aitra-score"><span>AI SCORE</span><b>${report.score==null?'—':Math.round(Number(report.score))}</b><i class="${sentiment}">${escapeHTML(sentiment.toUpperCase())}</i></div></header>
    <div class="aitra-asset-row"><div><span>TOKEN</span><b>${escapeHTML(token.symbol||'MARKET')}</b><small>${escapeHTML(token.name||'')}</small></div><div><span>CHAIN</span><b>${escapeHTML(token.chain||'MULTI-CHAIN')}</b></div>${token.address?`<div class="address"><span>ADDRESS</span><b>${escapeHTML(token.address)}</b></div>`:''}<div><span>DATA STATUS</span><b class="data-${escapeHTML(report.data_status||'partial')}">${escapeHTML(({complete:'COMPLETE',partial:'PARTIAL',unavailable:'NO QUALIFYING RESULT'}[report.data_status]||'PARTIAL'))}</b></div></div>
    ${metrics.some(([,value])=>value!=null&&value!=='—')?`<section class="aitra-report-section"><h3>MARKET</h3><div class="aitra-metrics">${metrics.filter(([,value])=>value!=null&&value!=='—').map(([label,value])=>`<div><span>${label}</span><b>${escapeHTML(value)}</b></div>`).join('')}</div></section>`:''}
    <div class="aitra-report-columns"><section class="aitra-report-section"><h3>RISK &amp; SMART MONEY</h3>${riskLevel!=='unknown'?`<div class="aitra-state-row"><span>Risk</span><b class="risk-${riskLevel}">${escapeHTML(riskLevel.toUpperCase())}</b></div>`:''}${smart.status&&smart.status!=='unavailable'?`<div class="aitra-state-row"><span>Smart Money</span><b>${escapeHTML(String(smart.status).toUpperCase())}</b></div>`:''}${asArray(risk.flags).length?`<ul>${asArray(risk.flags).slice(0,8).map(flag=>`<li>${escapeHTML(flag)}</li>`).join('')}</ul>`:'<p class="unavailable">No active risk flags in this report.</p>'}</section>
    <section class="aitra-report-section"><h3>DERIVATIVES / ON-CHAIN</h3>${derivativeRows.filter(([,value])=>value!=null&&value!=='').map(([key,value])=>`<div class="aitra-state-row"><span>${escapeHTML(key.replaceAll('_',' '))}</span><b>${escapeHTML(fmt(value))}</b></div>`).join('')||'<p class="unavailable">No derivative metric applies to this analysis.</p>'}</section></div>
    <section class="aitra-report-section"><h3>KEY INSIGHTS</h3><ol class="aitra-insights">${asArray(report.key_insights).filter(Boolean).map(item=>`<li>${escapeHTML(String(item).replace(/—/gi,'No observation returned'))}</li>`).join('')||'<li>No qualifying signal was observed in this scan.</li>'}</ol></section>
    <footer><div><span>DATA SOURCES</span>${asArray(report.data_sources).map(source=>`<i>${escapeHTML(source.name||'Source')} · ${escapeHTML(source.status||'unknown')}</i>`).join('')||'<i>—</i>'}</div><div><span>UPDATED</span><b>${escapeHTML(report.updated_at||'—')}</b><small>${escapeHTML(report.freshness||'')}</small></div><p>${escapeHTML(report.disclaimer||'Crypto intelligence only. Not financial advice.')}</p></footer></article>`;
}

export async function renderChat(root){
  const terminal=root.closest('.terminal');terminal?.classList.add('aitra-route');
  const state={mode:'assistant',core:'idle',statusText:'Engine ready',profile:{ai_name:'AITRA'},report:null,message:'',error:'',history:[],busy:false,selectedIntent:'',status:null,hasAnalysis:false,controller:null};
  const loadStatus=async()=>{try{state.status=asObject(await api.aitraStatus());state.profile={ai_name:'AITRA',...asObject(state.status.profile)}}catch{state.status={engine:{status:'degraded'},services:{},access:{tier:'free',badge:'Free',capabilities:[]},usage:{used:0,remaining:0}};state.profile={ai_name:'AITRA'}}};
  await loadStatus();
  if(!isMounted(root))return;
  const setCore=(name,text)=>{state.core=name;state.statusText=text||name;const core=root.querySelector('#aitraCore');if(core){core.dataset.state=name;core.setAttribute('aria-label',`AITRA AI Core status: ${name}`)}const label=root.querySelector('#aitraCoreState');if(label)label.textContent=state.statusText};
  const paint=()=>{
    const access=asObject(state.status.access),usage=asObject(state.status.usage),services=asObject(state.status.services),engine=asObject(state.status.engine),capabilities=asArray(access.capabilities);
    const alpha=state.mode==='alpha',modeAvailable=asArray(access.allowed_modes).includes(state.mode),modeActions=MODE_ACTIONS[state.mode];
    root.innerHTML=`<div class="aitra-terminal mode-${state.mode} ${state.hasAnalysis?'has-analysis':'is-empty'}">
      <header class="aitra-page-head"><div><span>${alpha?'ADVANCED CRYPTO INTELLIGENCE':'CRYPTO INTELLIGENCE ASSISTANT'}</span><h1>${alpha?'AITRA Alpha Engine':'AITRA Assistant'}</h1><p>${alpha?'Advanced Market Intelligence System · dense validated reports and approved research tools.':'Crypto Intelligence Assistant · fast token, market and risk answers.'}</p></div><div class="aitra-mode" role="tablist"><button data-mode="assistant" class="${!alpha?'active':''}" role="tab"><b>AITRA Assistant</b><small>Fast · ${access.assistant_limit<0?'Unlimited':`${access.assistant_limit||0} credits`}</small></button><button data-mode="alpha" class="${alpha?'active':''}" role="tab"><b>AITRA Alpha Engine</b><small>${asArray(access.allowed_modes).includes('alpha')?'Advanced access':'Locked permission'}</small></button></div></header>
      <div class="aitra-layout"><main class="aitra-main"><section class="aitra-core-zone">${coreHTML(state.profile.ai_name)}<div class="aitra-core-copy"><b>AITRA Intelligence Engine</b><span id="aitraCoreState">${escapeHTML(state.statusText)}</span><small>Powered by AITRACEROOT Intelligence Engine</small></div></section>
        ${!modeAvailable?`<div class="aitra-mode-locked"><div><b>${alpha?'Alpha Engine requires a verified wallet':'Assistant access is unavailable'}</b><span>${escapeHTML(access.advanced_locked_reason||'Connect and sign with an authorized wallet to load its Intelligence permissions.')}</span></div><button type="button" id="aitraVerifyWallet">CONNECT &amp; VERIFY WALLET</button></div>`:''}<section class="aitra-actions" aria-label="Quick Intelligence actions">${ACTIONS.filter(row=>modeActions.includes(row[0])).map(([intent,label,prompt])=>`<button data-action="${intent}" data-prompt="${escapeHTML(prompt)}" class="${state.selectedIntent===intent?'active':''}" ${!capabilities.includes(intent)?'disabled':''}><i></i><b>${label}</b><span>${capabilities.includes(intent)?'AVAILABLE':'LOCKED · PERMISSION REQUIRED'}</span></button>`).join('')}</section>
        <form class="aitra-command" id="aitraCommand"><div><span>${alpha?'ALPHA INTELLIGENCE COMMAND':'INTELLIGENCE COMMAND BAR'}</span><textarea id="aitraInput" rows="1" placeholder="${alpha?'Investigate smart money, alpha, on-chain, derivatives or compare tokens...':'Ask about a token, market, wallet, risk or crypto news...'}" aria-label="Intelligence command" ${!modeAvailable?'disabled':''}></textarea></div>${state.busy?'<button id="aitraCancel" type="button" class="cancel">CANCEL</button>':''}<button id="aitraSubmit" type="submit" ${state.busy||!modeAvailable?'disabled':''}>${state.busy?'ANALYZING…':alpha?'RUN ALPHA ANALYSIS':'RUN ANALYSIS'}</button></form>
        <div class="aitra-scope-note">Crypto Intelligence scope only · Complete reports consume one Analysis Credit · Validation failures and blocked requests are not charged</div>
        <section class="aitra-output" aria-live="polite">${state.report?reportHTML(state.report):state.message?`<div class="aitra-system-message"><b>${escapeHTML(state.error?'REQUEST NOT COMPLETED':'AITRA')}</b><p>${escapeHTML(state.message)}</p></div>`:`<div class="aitra-empty-copy"><b>Issue a Crypto Intelligence command</b><p>Analyze a token, scan a contract, summarize the market, or investigate on-chain activity.</p></div>`}</section>
        ${state.history.length?`<section class="aitra-history"><h2>SESSION INTELLIGENCE</h2>${state.history.map(item=>`<button data-history="${escapeHTML(item.id)}"><span>${escapeHTML(item.intent.replaceAll('_',' '))}</span><b>${escapeHTML(item.title)}</b><small>${escapeHTML(item.time)}</small></button>`).join('')}</section>`:''}
      </main><aside class="aitra-side"><details open><summary>AI STATUS</summary>${[['AI Engine',engine.status||'degraded'],['Market Data',services.market_data||'unavailable'],['On-Chain Data',services.onchain_data||'unavailable'],['Risk Engine',services.risk_engine||'unavailable'],['Smart Money',services.smart_money||'unavailable']].map(([label,value])=>`<div class="aitra-side-row"><span>${label}</span><b class="${/online|connected|active|tracking|ready/.test(value)?'up':'warn'}">${escapeHTML(String(value).toUpperCase())}</b></div>`).join('')}</details>
        <details open><summary>AI TOOLS</summary>${ACTIONS.slice(0,5).map(([intent,, ,tool])=>`<div class="aitra-side-row"><span>${tool}</span><b>${capabilities.includes(intent)?'READY':'LOCKED'}</b></div>`).join('')}<div class="aitra-side-row"><span>Derivatives Analyzer</span><b>${capabilities.includes('DERIVATIVES_ANALYSIS')?'READY':'LOCKED'}</b></div></details>
        <details open><summary>INTELLIGENCE ACCESS</summary><div class="aitra-access"><span>${escapeHTML(access.badge||'Free Access')}</span><b>${escapeHTML(access.access_label||'Basic Intelligence')}</b><p>Source: ${asArray(access.sources).includes('whitelist')?'Verified wallet whitelist':asArray(access.sources).includes('admin')?'Administrator policy':asArray(access.sources).includes('nft')?'Eligible Badge':'Free access'}</p></div><div class="aitra-credit"><span>ASSISTANT / ALPHA CREDITS</span><b>${access.unlimited_access?'UNLIMITED':`${access.assistant_limit||0} / ${access.alpha_engine_limit||0}`}</b><small>${Number(usage.used||0)} used today · reset ${escapeHTML(usage.reset_at||'daily UTC')}</small>${access.expires_at?`<small>Permission expires ${new Date(access.expires_at*1000).toLocaleString()}</small>`:''}</div></details></aside></div></div>`;
    root.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{state.mode=button.dataset.mode;paint()});
    root.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{state.selectedIntent=button.dataset.action;const input=root.querySelector('#aitraInput');input.value=button.dataset.prompt;input.focus();paintActionState()});
    root.querySelector('#aitraCommand').onsubmit=run;
    const verify=root.querySelector('#aitraVerifyWallet');if(verify)verify.onclick=()=>window.dispatchEvent(new CustomEvent('atr:verify-wallet'));
    const cancel=root.querySelector('#aitraCancel');if(cancel)cancel.onclick=()=>state.controller?.abort();
    root.querySelector('#aitraInput').onkeydown=event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();run(event)}};
    root.querySelectorAll('[data-history]').forEach(button=>button.onclick=()=>{const item=state.history.find(row=>row.id===button.dataset.history);if(item){state.report=item.report;state.message='';paint()}});
    setCore(state.core,state.statusText);
  };
  const paintActionState=()=>root.querySelectorAll('[data-action]').forEach(button=>button.classList.toggle('active',button.dataset.action===state.selectedIntent));
  const run=async event=>{
    event?.preventDefault();if(state.busy)return;
    const input=root.querySelector('#aitraInput'),query=input?.value.trim();if(!query){input?.focus();return}
    state.busy=true;state.controller=new AbortController();state.report=null;state.message='';state.error='';setCore('analyzing','Analyzing intent and scope');paint();setCore('tool-calling',state.selectedIntent?`Calling ${ACTIONS.find(row=>row[0]===state.selectedIntent)?.[3]||'approved tool'}`:'Routing approved data tools');
    try{const output=await api.aitraAnalyze(query,state.mode,state.selectedIntent,requestId(),state.controller);state.selectedIntent='';if(output.kind==='report'&&output.report){setCore('completed','Report validated');state.report=output.report;state.hasAnalysis=true;state.history.unshift({id:output.request_id,intent:output.intent,title:output.report.title,time:new Date().toLocaleTimeString('en-US',{hour12:false}),report:output.report});state.status.usage.used=Number(state.status.usage.used||0)+(output.charged?1:0);if(state.status.usage.remaining!=null&&output.charged)state.status.usage.remaining=Math.max(0,Number(state.status.usage.remaining)-1)}else{state.message=output.text||output.error||'AITRA could not complete this request.';state.error=!output.ok;setCore(output.ok?'completed':'error',output.ok?'Request handled without analysis':'Request not completed')}}catch(error){state.message=error?.message||'AITRA could not complete this request.';state.error=true;setCore('error',/cancelled/i.test(state.message)?'Request cancelled':'Intelligence request failed')}
    state.busy=false;state.controller=null;paint();setTimeout(()=>{if(isMounted(root))setCore('idle','Engine ready')},900);
  };
  const walletChanged=async()=>{await loadStatus();if(!isMounted(root))return;const access=asObject(state.status.access);if(state.mode==='alpha'&&!asArray(access.allowed_modes).includes('alpha'))state.message='Wallet connected, but Alpha Engine permission is not enabled for this wallet.';else state.message='';state.error='';paint()};
  window.addEventListener('wallet-session-change',walletChanged);
  paint();
  return ()=>{state.controller?.abort();window.removeEventListener('wallet-session-change',walletChanged);terminal?.classList.remove('aitra-route')};
}
